name: Deploy to GitHub Pages

# 触发条件：每次 push 到 master 分支时触发
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'



    - name: Install and Build
      run: |
          yarn 
          yarn build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        personal_token: ${{ secrets.GH_PAT }}
        branch: master
        folder: docs # npm run build-storybook输出的文件夹



