name: Deploy to GitHub Pages

# 触发条件：每次 push 到 master 分支时触发
on:
  push:
    branches:
      - master
permissions:
  pages: write  # 赋予写入 GitHub Pages 的权限
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install and Build
      run: |
          yarn 
          yarn build

    # - name: Upload build artifacts
    #   uses: actions/upload-pages-artifact@v3
    #   with:
    #     path: ./docs
    #     name: github-pages
    #     retention-days: 1

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        #artifact_name: github-pages



